# Generated by Django 5.1.1 on 2025-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('password', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationsTable',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('field_email', models.CharField(db_column=' email')),
                ('phoneno', models.CharField(max_length=10)),
                ('password', models.CharField()),
                ('address', models.CharField()),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'registrations_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('service_creation_date', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField()),
                ('v_video', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_table',
                'managed': False,
            },
        ),
    ]
